### ISSUE TITLE
How can ,I change this code so that it can send mails to others.

### ISSUE THREAD

**Issue by abheer18** [victoria-lo/Nodemailer-Tutorial#1]
Could you please tell me that how can I change this code so that I can send email to others as well.
Please help me @victoria-lo

**Comment by realabdullah** [comment]
In the server.js file, replace the service with your intended service provider and in your environment variables, fill with the auth details of your intended email address.

**Comment by victoria-lo** [comment]
Closed due to solution already provided. Thanks!
