### ISSUE TITLE
bad path to file

### ISSUE THREAD

**Issue by mjwdavis** [victoria-lo/Nodemailer-Tutorial#4]
https://github.com/victoria-lo/Nodemailer-Tutorial/blob/c0dd3983c705ccbc3b561d1be43c7f898b7bf4f2/public/index.html#L103

Path should be /public/index.js since it's referenced in an express template. Thank you for the tutorial, it was very helpful!

**Comment by victoria-lo** [comment]
Thanks for the correction :)
